### PR TITLE
Throw some reasonable error message in basic authentication when we c…

### PR DESCRIPTION
**Pull request by tremes**
…an't obtain an access token.

### CODE REVIEW

**Comment by tremes** [comment]
We have seen errors like (e.g when there's an extra slash at the end of login url)
``` 
Uncaught TypeError: Cannot read property 'indexOf' of null
      at Request.request [as _callback] (/home/trepel/work/githubRepos/integreatly-qe/test-suites/utils/node_modules/openshift-rest-client/lib/basic-auth-request.js:34:31)
```
This is a proposal to improve the error message. Maybe we can display full (href) url with username and password in the error message?

**Comment by tremes** [comment]
@lholmquist np and thanks. OK so I can try to improve the error message little bit.

**Comment by lholmquist** [comment]
> OK so I can try to improve the error message little bit.

Go for it.  i'll wait to merge then

**Comment by tremes** [comment]
Updated.

**Comment by lholmquist** [comment]
released as 3.0.1

**Pull request merged**
