### PR TITLE
feat: use a username/password combo to login

### LINKED ISSUE #117: Use Basic Auth with the client
This was a feature in the 1.x branch,  a user can supply a username and password instead of an access token, and things would work.

With the new client, this doesn't work, since the auth endpoint for Openshift is a different endpoint.

I think this should be possible,  we first need to "authenticate" with the username and password, then get the token,  then "create" the client with a custom config.

### PR DESCRIPTION
**Pull request by lholmquist**
fixes #117

### CODE REVIEW

**Comment by tremes** [comment]
Is this addressing https://github.com/nodeshift/openshift-rest-client/issues/117? Shall I verify this pr?

**Comment by lholmquist** [comment]
@tremes hi, yes.  if you wouldn't mind.  if you would like for me to release a pre-release with this change, let me know,  it might be easier to test that way

**Comment by tremes** [comment]
ok I think I can do it without a pre-release...hopefully. Thanks I'll check and let you know

**Comment by lholmquist** [comment]
I also need to update the readme with an example, to make it clear how to use this

**Comment by lholmquist** [comment]
Something like this should work

```
const openshiftRestClient = require('openshift-rest-client').OpenshiftClient;


(async function () {
  const settings = {
  };

  settings.config = {
    url: process.env.CLUSTER_URL,
    auth: {
      username: process.env.ADMIN_USERNAME,
      password: process.env.ADMIN_PASSWORD
    },
    insecureSkipTlsVerify: true
  };

  const client = await openshiftRestClient(settings);

  const projects = await client.apis['build.openshift.io'].v1.ns('myproject').builds.get();
  console.log(projects);
})();
```

**Comment by tremes** [comment]
OK thanks. I think I'll try it tomorrow....

**Comment by tremes** [comment]
@lholmquist OK so it worked for me. I think I can progress with migration of our testsuite to v2.0 once this is merged.

**Pull request merged**
