### PR TITLE
fix: preparation godaddy/kubernetes-client upgrade to 9.x

### PR DESCRIPTION
**Pull request by evanshortiss**
Addresses #162

### CODE REVIEW

**Comment by lholmquist** [comment]
@evanshortiss thanks for this.   

something else might want to address is if Nodeshift should be locking the versions of it dependecies instead of allowing it to get patch level updates,  but i'll add that as a Nodeshift issue

**Comment by lholmquist** [comment]
I noticed that in one of the tests, a deprecation warning is now popping up,

```
test basic auth - username/password

    ✔ should be equal
    ✔ should be equal
    ✔ should be equal
kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md lib/openshift-rest-client.js:89:40
    ✔ (unnamed assert)
```

I'm somewhat tempted to revert the changes that were made, and release a new patch version,  which nodeshift should get if you remove the package-lock again.

Then we can have more time to figure this all out

**Comment by lholmquist** [comment]
@evanshortiss @helio-frota would like to here your thoughts here

**Comment by helio-frota** [comment]
@lholmquist sounds like a good approach :+1:

**Comment by lholmquist** [comment]
@evanshortiss i reverted the changes from that other PR #160 and released a new 2.2.2 version.  you should be able to get this new updated version if you remove your package-lock and do an install again

**Comment by evanshortiss** [comment]
Yep I'm ok with whatever works for you folks to get a fix out. That log message is what I got locally and tipped me off to the fix.

It seems like you don't need to lock the deps, it was a major update in the Kubernetes rest client dep of the OpenShift rest client so maybe the OpenShift rest client should have bumped major/minor instead of patch? It's one of those issues where it's tough to decide on the answer.

**Comment by evanshortiss** [comment]
@lholmquist closing this since I think you folks are going to take it from here.

**Pull request closed without merging**
