### PR TITLE
Node.js version updates

### PR DESCRIPTION
**Pull request by BethGriggs**

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Comment by helio-frota** [comment]
what if we add npm install before the npm ci ?

that worked for me with the chokidar problem

```
❯ npm --version ; node --version
6.14.13
v14.17.0
openshift-rest-client on  main is 📦 v7.0.0 via  v14.17.0 
❯ npm ci
npm ERR! fsevents not accessible from chokidar

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lm/.npm/_logs/2022-08-24T17_28_41_293Z-debug.log
openshift-rest-client on  main is 📦 v7.0.0 via  v14.17.0 
❯ npm i
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lm/.npm/_logs/2022-08-24T17_28_47_253Z-debug.log
openshift-rest-client on  main is 📦 v7.0.0 via  v14.17.0 
❯ rm package-lock.json 
openshift-rest-client on  main [✘] is 📦 v7.0.0 via  v14.17.0 
❯ npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lm/.npm/_logs/2022-08-24T17_29_06_803Z-debug.log
openshift-rest-client on  main [✘] is 📦 v7.0.0 via  v14.17.0 
❯ npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> openshift-rest-client@7.0.0 prepare /home/lm/code/openshift-rest-client
> husky install

husky - Git hooks installed
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 943 packages from 531 contributors and audited 945 packages in 9.488s

178 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
openshift-rest-client on  main [!] is 📦 v7.0.0 via  v14.17.0 took 10s 
❯ npm ci
npm WARN prepare removing existing node_modules/ before installation

> openshift-rest-client@7.0.0 prepare /home/lm/code/openshift-rest-client
> husky install

husky - Git hooks installed
added 944 packages in 3.71s
```

**Comment by helio-frota** [comment]
removing package-lock.json is better than global npm 
https://github.com/nodeshift/openshift-rest-client/pull/310

**Review by helio-frota — APPROVED** [review]

**Comment by BethGriggs** [comment]
@helio-frota I think I resolved the issue by generating the `package-lock`

**Comment by helio-frota** [comment]
@BethGriggs awesome :100:

**Comment by helio-frota** [comment]
now we can take a better look on the dependencies at least

**Pull request merged**
