### PR TITLE
chore: adding the contributing guide

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by helio-frota** [comment]
basically almost the same document for example https://github.com/nodeshift/nodeshift/blob/main/CONTRIBUTING.md

**Comment by helio-frota** [comment]
I'm going to merge because we missed to add this file

**Comment by BethGriggs** [comment]
@helio-frota we should really wait for at least one review on all PRs.

**Comment by helio-frota** [comment]
@BethGriggs sounds good :+1:  thanks

**Pull request merged**
