### PR TITLE
chore: update workflow Node.js versions

### PR DESCRIPTION
**Pull request by BethGriggs**

### CODE REVIEW

**Review by helio-frota — APPROVED** [review]
:100:

**Comment by BethGriggs** [comment]
This wasn't ready to merge

**Comment by BethGriggs** [comment]
99a577bf0c20b346560a70259caa47fdefe3fbf3 added a step to the GitHub Actions to globally update `npm@latest`, which means Node.js 14 + npm 6 combination is no longer being tested, which this PR needs to test.

**Comment by helio-frota** [comment]
got it thanks for the info :+1:

**Pull request merged**
