### PR TITLE
#98 print some meaningful error message in case of unsuccessful authe…

### PR DESCRIPTION
**Pull request by tremes**
…ntication

connects to #98

### CODE REVIEW

**Comment by lholmquist** [comment]
looks good, but can we actually add a test for this.  you should be able to mock the request lib with proxyquire, which is a dev dependecies already.

**Comment by tremes** [comment]
I don't know how proxyquire can help me TBH. I think I need to use real credentials (on minishift I guess) to test successful as well as unsuccessful authentication.

**Comment by lholmquist** [comment]
since all we have are unit tests, proxyquire would allow us to mock the request library(the thing that actually makes the http calls), and just test a mocked response.  I actually might make this another GH issue, since it would be testing more that just this updated functionality

**Comment by lholmquist** [comment]
new issue for the tests here #100

**Comment by lholmquist** [comment]
@tremes i just released 1.6.1 with the fix

**Comment by tremes** [comment]
Thanks @lholmquist

**Pull request merged**
