### PR TITLE
Attach current auth token to the client config

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
@lholmquist  what do you please think about it? I realized I wasn't able to obtain current token value from the config or am I wrong again? :)

**Comment by lholmquist** [comment]
was this meant for the 1.x branch?

**Comment by tremes** [comment]
@lholmquist yes. It's open against 1.x if I am not mistaken.

**Comment by lholmquist** [comment]
Just looking at this,  it looks like you will only be able to access the token after you make a request to an API.  

i haven't tested it yet

**Comment by tremes** [comment]
Yes it's likely true. I already switched to v2.1.0 so this is not a blocker for me. Maybe we can close it? On the other hand it might helpful...at least little bit:-)

**Comment by lholmquist** [comment]
closing for now,  if needed we can re-open

**Pull request closed without merging**
